base_images:
  os:
    name: ubi
    namespace: ocp
    tag: "8"
binary_build_commands: make build
build_root:
  project_image:
    dockerfile_path: openshift-ci/Dockerfile.tools
images:
- dockerfile_path: openshift-ci/Dockerfile.deploy
  from: os
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift-kni/performance-addon-operators/build/_output/bin/performance-addon-operators
  to: debug-tools
promotion:
  name: debug-tools
  namespace: ocp-kni
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.7"
  namespace: ocp
tests:
- as: ci
  commands: make ci-job
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: openshift-kni
  repo: debug-tools
